name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.7]
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          run: go version
      - name: Test
        run: go test ./tests
        env:
          STARCOIN_ES_URL: ${{ secrets.STARCOIN_ES_URL }}
          STARCOIN_ES_USER: ${{ secrets.STARCOIN_ES_USER }}
          STARCOIN_ES_PWD: ${{ secrets.STARCOIN_ES_PWD }}
